import "./globals.css";

export const metadata = {
  title: "Apicts FX",
  description: "Generated by create next app",
  verification: {
    google: "ND7gkGw6-n-cVQjeoFeAHv9_vN0R-5s5T6jzn_MbR-w"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
